"""Initial migration.

Revision ID: 8c822ed19f01
Revises: 
Create Date: 2023-08-23 16:33:25.477685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c822ed19f01'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('passwordHash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('logo', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('userFID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userFID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchasedAdvertisings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('channelLink', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('numberOfNewSubs', sa.Integer(), nullable=True),
    sa.Column('channelFID', sa.Integer(), nullable=False),
    sa.Column('userFID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channelFID'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['userFID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soldAdvertisings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('channelLink', sa.String(length=128), nullable=False),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('numberOfSubs', sa.Integer(), nullable=True),
    sa.Column('channelFID', sa.Integer(), nullable=False),
    sa.Column('userFID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['channelFID'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['userFID'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soldAdvertisings')
    op.drop_table('purchasedAdvertisings')
    op.drop_table('channels')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
